#+TITLE: Welcome to haider.gq

* Welcome to haider.gq
** Who Am I?
#+begin_src
  _   _ __  ___
 | | | |  \/  |
 | |_| | |\/| | My Github: https://github.com/Ha1derMirza
 |  _  | |  | | My Matrix: @haider.mirza:matrix.org
 |_| |_|_|  |_|
#+end_src
My Name is Haider Mirza and I am a 3D artist, Programmer and Emacs devotee.
All my projects (included this website) are cloned/hosted on [[https://github.com/Ha1derMirza][github]] and are free and open-source under the GPL v3 license.

** About this website
This website is hosted on github pages (Here: [[https://github.com/Ha1derMirza/Ha1derMirza.github.io][Website]])
It also contains many things like:
- Notes
- Information
- Documents for use of others

** My Git repositories
*** Note:
There are some things you might notice with my Repositories:
**** Minimal Distractions
I don’t want things on the screen that are unrelated to what I’m doing. I very rarely display more than one buffer or window on the main screen at a time. Emacs makes it easy and fast to switch between open buffers (and workspaces in EXWM) so there’s really no reason to have two unrelated things visible on the screen.

**** Text-based Configuration
I really don’t want to use a program that doesn’t support text-based configuration files. I also prefer tools that don’t write out those configuration files on my behalf. This enables me to commit program configuration to source control (this repository) so that I can keep configurations in sync on every machine that I use.

**** Highly Customizable
To perfect my computing workflow, I choose tools that allow me to customize them to fit in smoothly with everything else. Emacs is the most faithful adherent to this principle as it allows you to intercept or replace the code for just about anything it does. For other programs, I like to use tools that are either scriptable by some means or enable to you call out to another process (or shell script) to gather information. Vimb and Polybar both do this, so it’s pretty easy to integrate them into the rest of my workflow.
*** The Repositories
**** [[https://www.haider.gq/repos/Dotfiles.html][Dotfiles]]
**** [[https://www.haider.gq/repos/Scripts.html][Scripts]]
**** [[https://www.haider.gq/repos/Wallpapers.html][Wallpapers]]
**** [[https://www.haider.gq/repos/Documents.html][Documents]]
**** [[https://www.haider.gq/repos/Blender.html][Blender-Projects]]
**** [[https://www.haider.gq/repos/Website.html][Ha1derMirza.github.io]]
**** [[https://www.haider.gq/repos/Ha1derMirza.html][Ha1derMirza]]
** Notes
I write Notes for many of the programs I use.
Here are a list of them if you need any of the information I have learnt the hard way.
You can Also find this in my [[https://github.com/Ha1derMirza/Documents][Documents]] repository.

Here are some of the notes I have written:
- [[https://www.haider.gq/Notes/EXWM.html][EXWM]]
- [[https://www.haider.gq/Notes/Mu4e.html][Mu4e]]
- [[https://www.haider.gq/Notes/FFmpeg.html][FFmpeg]]
- [[https://www.haider.gq/Notes/OrgMode.html][OrgMode]]
- [[https://www.haider.gq/Notes/OrgRoam.html][OrgRoam]]
