#+TITLE: Public Speaking
#+AUTHOR: Haider M
#+DATE: [2022-02-24 Thu]

Worldwide food production, is responsible for 26% of all human made greenhouse gas emmitions.
One of the most favourite portion of food, meat gains one of the worst backlash by climate change activists.
So should we begin to embrace vegetarianism?

Well, it's complicated.
Firstly is that it is hard to force anyone anything, as we can see with the current state with Russia declaring war on ukrane and with the covid vaccine.
We could try adopting the congestion charge system at work with food, but again this is difficult becuase food expresses culture,
celebration or comfort and that is why it annoys people when we have to change what we eat to fight rapid climate change.

But does our diet really play a big role in climate change?
Sadly, it's impossible to feed a planet of billions of people without creating emmissions.   
Even if we use 0-carbon tractors, refrigoratiors, cookers and trucks. there are still unavoidable emmitions.
Like: rice emmitting methane, cutting down trees to make space for pastures and crops.
And we even emmit nitrous oxide when we use firtilizers and manure.

In 2018, a study showed that Worldwide food production is responsible for 26% of all human made greenhouse gas emmitions.
This is unfortuanate, especially when food is not optional. While 26% doesnt seem that bad, even if we estinguish all other sources of emmisions today,
The emissions from food alone would still use up our entire carbon budget by 2100.

As we can see, food is a huge cause of climate change.
Emmissions, however, vary between food items alot
We use something called a life cycle assessment to measure all the emmitions of a product throughout it's existance.

A life cycle assessment of beef shows that it emits the equavialent of 71 kilograms of CO2.
Lamb is also high with 40 kilograms.
Pork emits 12Kilograms.
And at the bottom we have alot of plant based foods like potatoes which emit about 150 times less than beef.
However, the most important of food isnt weight though, it's neutrient density.
A kilogram of beef would keep you alive much longer than a kilogram of potatoes.

If we compare emissions with calorie or protein the situation relatively the same, meat is still the largest food carbon emitter.

But every beef is different, The worst beef creats 105kilograms of emissions per 100 grams of protein.
And the best creats only 9kilograms, a difference of 12 times.
Beef is still bad however with the best beef being worse than the worst plant by about 2 times.

Most beef emisstions producer is the cows themselves who emit methane,
whist CO2 hangs around in the atmosphere for centuries, methane stays for only decades.
But in these short periods, it is very powerful with contributing and causes up to 40% of human made warming so far.

No matter what we do, food is a real cause of climate change
It's too late to just mend our ways, we have to actively correct our past mistakes.
So what should we do?

Eating less meat wont stop climate change but we cant stop climate change without eating less meat.
You could try eating less meat or regulating your diet. But what should happen is for there to be a fix to the entirety of climate change not a small aspect of it.

What should happen is for us to pressure the people in power. Politicians need to know and feel that the people care and make it so their own success depends on tackiling rapid climate change.
And if governments and local politicians are reluctant to change laws that effect their largest tax contributors or campaign donors, we need to vote them out and vote in people who actually respect science.
We need to hold them accountable for implementing the most effective climate change strategies. In principle, technology already exists, direct air capture of co2 draws carbon dioxide from the air so it can be stored underground or transformed into products.
The reason why this technology is not largely implemented, at the current state of technology, this will about 10 trillion dollars per year or in other words, half of the united state's GDP.
Nobody is liking this investment. Other methords like: Algae Biofuel and Tidal Energy still need alot of time and research which means that they are expensive.

Back to the question, should we all begin to embrace vegetarianism?
We should all give vegetarianism a try, we all need to do our part to try and slow down this new pandemic.
