#+TITLE: Expanding Brackets
#+AUTHOR: Haider M
:PROPERTIES:
#+OPTIONS: toc:t
:END:

* Expanding Brackets
To expand a bracket means to multiply each term in the bracket by the expression outside the bracket.
Below are two examples to help you understand this.

* Examples
** Note:
$4(x+2) = 4x+8$ (*These are both Equal*)

You can see why this works:

https://www.haider.gq/maths/Algebraic-products/Exp-Brack-1.png

** Example 1
$3y(x+4+z^2)$ 

*** Methord
We should solve this by going *left to right*. \\
This would still work if you complete this in a different order but left to right is reccomended.

1. $3y \times x = 3yx$
2. $3y \times 4 = 12y$
3. $3y \times z^2 = 3y7^2$

You can see this procedure below

https://www.haider.gq/maths/Algebraic-products/Exp-Brack-2.png
   
And then you collect all of the outputs and then you have expanded your brackets.

$3y(x+4+7^2)$ = $3yx+12y+3yz^2$


Again, you can visualise the brackets here:

https://www.haider.gq/maths/Algebraic-products/Exp-Brack-3.png
** Example 2
$(5z+1)(5z+2)$

*** Methord
Again we should solve this by going *left to right*. \\
This would still work if you complete this in a different order but left to right is reccomended.


Here where we have 2 brackets, the procedure is the same but with both of the elements in the brackets.

**** First Bracket
1. $5z \times 5z = 25z^2$
2. $5z \times 2 = 10z$

**** Second Bracket
1. $1 \times 5z = 5z$
2. $1 \times 2 = 2$

You can see this procedure below:

https://www.haider.gq/maths/Algebraic-products/Exp-Brack-4.png
