:PROPERTIES:
:ID:       5ef92870-2c07-48e5-88b7-e75ef13aa159
:END:
#+title: circuits
#+date: [2022-05-12 Thu 21:28]

* Electrical circuits
** Current
An electric current is a stream of charged particles, such as electrons or ions, moving through an electrical conductor or space.
*NOTE:* Electrons have a negative charge and flow from negative to postitive. (I know, I also used to make that mistake)
*** Calculating current
You can calculate current with the formula
Current is measured in Amps(A) and is represented as 'I'.

$Current = \frac{charge}{time}$
or:
$I = \frac{Q}{T}$
** Resistance
Passing electrons have to try and move their way accross many vibrating elections.
The atoms try and stop the electrons from passing like fighting against a strong gale. 
** Series Circuits
In fully series circuits, the current at any point in the circuit is the same.
Ampmeters are usually connected in series as a Ampmeter measures current and has a very low resistance.
** Parallel Circuits
Current gets *shared* between branches but voltage stays the *same*.
A Voltmeter should always be connected in Parallel because of it's large resistance.
