:PROPERTIES:
:ID:       5ef92870-2c07-48e5-88b7-e75ef13aa159
:END:
#+title: Circuits
#+date: [2022-05-12 Thu 21:28]

* Electrical circuits
** Voltage
Voltage is the amount of energy in Joules avalable to move 1 coulumb of charge.

$Voltage = \frac{work(energy)}{q(charge)}$
** Electric charge
Charles-Augustin de Coulomb said that there was obviously something flowing inside a conductive medium like a fluid and let's call that electric charge.
The unit for electric charge is Coulomb, and it's symbol is "q".
*** Coulomb's Law
I really wont go into this as I do not understand it enough but here is the gist of it:
[https://www.haider.gq/images/do-not-delete/Notes/coloumb-law]
$F = K_e \frac{q_1 * q_2}{r^2}$
** Current
An electric current is a stream of charged particles, such as electrons or ions, moving through an electrical conductor or space.
*NOTE:* Electrons have a negative charge and flow from negative to postitive. Current is positive to negative.
(When scientists discovered that electron moves from negative to positive instead of positive to negative, they just left current as it is as all calculations will still work)

At it's core, Current is the amount of charge in coulomb passing in one second

*** Calculating current
You can calculate current with the formula
Current is measured in Amps(A) and is represented as 'I'.

$Current = \frac{charge}{time}$
or:
$I = \frac{Q}{T}$
** Resistance
Passing electrons have to try and move their way accross many vibrating elections.
The atoms try and stop the electrons from passing like fighting against a strong gale. 
** Series Circuits
In fully series circuits, the current at any point in the circuit is the same.
Ampmeters are usually connected in series as a Ampmeter measures current and has a very low resistance.
** Parallel Circuits
Current gets *shared* between branches but voltage stays the *same*.
A Voltmeter should always be connected in Parallel because of it's large resistance.
