:PROPERTIES:
:ID:       f8b81c21-7c7e-410e-82ad-046fa5fa4c55
:END:
#+title: Emacs
#+date: [2022-03-25 Fri 07:00]
* Emacs
GNU Emacs isn’t a text editor, it’s the ultimate productivity environment for hackers.
** Emacs Packages
Emacs is Incredibly extensive and there are 1000s of packages people have made for it,
Here is a note on some I have documented: [[id:9198649d-5d1d-49fa-a84b-66f02797d8b4][Emacs Packages]]
** IDE
I Love Programming, and as a result, you would want a great IDE.
What's a better IDE than Emacs?
[[https://emacs-lsp.github.io/lsp-mode/][LSP-mode]] allows you to use Language Server Protocol (LSP) in Emacs. (That's pretty insane)
I mainly use [[https://emacs-lsp.github.io/lsp-mode/][LSP-mode]] with clangd (you can see more about clangd in [[id:6a25d10a-fc17-4659-a714-0b7716d9de25][CMake]])
** Some useful keybinds
*Note that on my system, 'CTRL' is re-keybinded to 'CAPS LOCK' for erganomic and speed benifits*

C-j for return
C-i for tab
** Email
Email in Emacs can use the [[id:d71d294a-b8e3-48e3-8295-3d373bcd9681][Mu4e]] package which I use with mbsyncrc
** Issues
*** Emacs can't find guix package
If I ever encounter that Emacs cant find a package installed by [[id:4ce84157-a404-40fa-bdb8-0b3923916969][Guix]], I found a tempoary solution online:
#+BEGIN_SRC elisp
(let ((default-directory  "/home/haider/.guix-extra-profiles/mail/mail/share/emacs/site-lisp"))
  (normal-top-level-add-subdirs-to-load-path))
#+END_SRC
