#+TITLE: EXWM
#+AUTHOR: Haider Mirza
#+DESCRIPTION: A Document Talking about EXWM.
#+LINK_HOME: index.html

* About EXWM
EXWM is a full X window manager, so Emacs manages X windows such as your browser, vlc, etc. You may use all the normal Emacs window commands to control window placement. In X windows (i.e. not "normal" Emacs buffers), some commands are caught by EXWM and not passed through to the program. These keys are store in exwm-input-prefix-keys. Alternatively, you can set global commands by customizing exwm-input-global-keys. If you would rather set exwm-input-global-keys in elisp rather than using the customization feature, be aware that you may have to restart EXWM (and set exwm-input-global-keys before enabling exwm). Alternatively, you could try using the cset macro defined here, which should work for redefining exwm-input-global-keys without restarting EXWM. To use s-& as a keyboard shortcut to launch a program (e.g. firefox), you can do:

* Using EXWM
I have commented out my previous EXWM config.
You can use my config or copy parts of it.
