:PROPERTIES:
:ID:       31a1bfc7-4500-46de-b83d-1a0119db26fd
:END:
#+title: Triple brackets
#+date: [2022-06-03 Fri 12:09]

* Triple Brackets
Sometimes, instead of having to deal with 2 brackets, we have to deal with *3*.
Here is an example: Expand $(x+2)(x+3)(x+7)$

This is quite daunting at first and you probably have no clue on what to do, but it's actually simple but lengthy.
I will show you how to do so in the following examples.

* Examples
** Example 1
I am going to use the same question as before.

Expand $(x+2)(x+3)(x+7)$

*** Step 1
All you have to do is expand two of the brackets. You can choose any two but generally you do the first two.
There are some occations where you should choose other two brackets to expand to make the question easier but generally we do the first two.

Expanding $(x+2)(x+3)$ will give us:
$x^2+5x+6$

Then we add back the rest of the equation giving us:
$(x^2+5x+6)(x+7)$

You can see the entire procedure here:
https://www.haider.gq/maths/Algebraic-products/Triple-brac-1.png
It's quite messy but you can understand what it is trying to say.

This still looks daunting but you should be fine. It is the same as what we did before

*** Step 2
Expand: $(x^2+5x+6)(x+7)$

We do these calculations:
$x^2 \times x = x^3$
$x^2 \times 7 = 7x^2$
$5x \times x = 5x^2$
$5x \times 7 = 35x$
$6 \times x = 6x$
$6 \times 7 = 42$

Then collect like terms: $x^3 + 7x^2 + 5x^2 + 35x + 6x + 42$
$= x^3 + 12x^2 + 41x + 42$

We finally got there! It was a long proccess but well worth it.
** Example 2
Here is an example: $(2x+1)^3$
This is one bracket, but as we see from [[file:Perfect-Squares.org][this webpage]], $(3x+1)^3$ actually means $(2x+1)(2x+1)(2x+1)$

*** Step 1
Like the previous example, we expand the first two brackets.
$2x \times 2x = 4x^2$
$2x \times 1 = 2x$
$1 \times 2x = 2x$
$1 \times 1 = 1$

Then we collect like terms, $4x^2 + 2x + 2x + 1$
$= 4x^2 + 4x + 1$

*** Step 2
We are not done yet, we still have the other bracket.
$(4x^2 + 4x + 1)(2x+1)$

Time to expand:
$4x^2 \times 2x = 8x^3$
$4x^2 \times 1 = 4x^2$
$4x \times 2x = 8x^2$
$4x \times 1 = 4x$
$1 \times 2x = 2x$
$1 \times 1 = 1$

Time to collect, $8x^3 + 4x^2 + 8x^2 + 4x + 2x + 1$
$= 8x^3 + 12x^2 + 6x + 1$

We are now done!
